import React, { useState, useEffect, useCallback } from 'react';

interface UrlSlugManagerProps {
    title: string;
    slug?: string;
    fullUrl?: string;
    type: 'service' | 'subservice' | 'page' | 'asset';
    parentSlug?: string;
    baseUrl?: string;
    onSlugChange: (slug: string) => void;
    onFullUrlChange: (fullUrl: string) => void;
    onValidationChange?: (isValid: boolean, warnings: string[]) => void;
    disabled?: boolean;
    placeholder?: string;
}

const UrlSlugManager: React.FC<UrlSlugManagerProps> = ({
    title,
    slug: initialSlug = '',
    fullUrl: initialFullUrl = '',
    type,
    parentSlug,
    baseUrl = '',
    onSlugChange,
    onFullUrlChange,
    onValidationChange,
    disabled = false,
    placeholder = 'Enter URL slug...'
}) => {
    const [slug, setSlug] = useState(initialSlug);
    const [fullUrl, setFullUrl] = useState(initialFullUrl);
    const [isAutoGenerated, setIsAutoGenerated] = useState(!initialSlug);
    const [isValid, setIsValid] = useState(true);
    const [warnings, setWarnings] = useState<string[]>([]);
    const [isChecking, setIsChecking] = useState(false);

    // Generate slug from title
    const generateSlugFromTitle = useCallback((text: string): string => {
        if (!text) return '';

        return text
            .toLowerCase()
            .replace(/[&]/g, 'and')
            .replace(/[^\w\s-]/g, '')
            .replace(/[\s_]+/g, '-')
            .replace(/-+/g, '-')
            .replace(/^-+|-+$/g, '')
            .substring(0, 100);
    }, []);

    // Generate full URL from slug
    const generateFullUrl = useCallback((slugValue: string): string => {
        if (!slugValue) return '';

        switch (type) {
            case 'service':
                return `/services/${slugValue}`;
            case 'subservice':
                if (parentSlug) {
                    return `/services/${parentSlug}/${slugValue}`;
                }
                return `/services/${slugValue}`;
            case 'page':
                return `/${slugValue}`;
            case 'asset':
                return `/assets/${slugValue}`;
            default:
                return `/${slugValue}`;
        }
    }, [type, parentSlug]);

    // Validate slug and URL
    const validateSlugAndUrl = useCallback((slugValue: string, urlValue: string) => {
        const newWarnings: string[] = [];
        let newIsValid = true;

        // Validate slug
        if (!slugValue) {
            newWarnings.push('Slug cannot be empty');
            newIsValid = false;
        } else {
            if (slugValue.length > 100) {
                newWarnings.push('Slug is too long (max 100 characters)');
                newIsValid = false;
            }

            if (!/^[a-z0-9-]+$/.test(slugValue)) {
                newWarnings.push('Slug contains invalid characters (only lowercase letters, numbers, and hyphens allowed)');
                newIsValid = false;
            }

            if (slugValue.startsWith('-') || slugValue.endsWith('-')) {
                newWarnings.push('Slug cannot start or end with a hyphen');
                newIsValid = false;
            }

            if (slugValue.includes('--')) {
                newWarnings.push('Slug cannot contain consecutive hyphens');
                newIsValid = false;
            }
        }

        // Validate full URL
        if (!urlValue) {
            newWarnings.push('Full URL cannot be empty');
            newIsValid = false;
        } else {
            if (!urlValue.startsWith('/')) {
                newWarnings.push('Full URL must start with /');
                newIsValid = false;
            }

            // Context-specific validation
            switch (type) {
                case 'service':
                    if (!urlValue.startsWith('/services/')) {
                        newWarnings.push('Service URL must start with /services/');
                        newIsValid = false;
                    }
                    break;
                case 'subservice':
                    if (parentSlug) {
                        const expectedPrefix = `/services/${parentSlug}/`;
                        if (!urlValue.startsWith(expectedPrefix)) {
                            newWarnings.push(`Sub-service URL must start with ${expectedPrefix}`);
                            newIsValid = false;
                        }
                    }
                    break;
            }
        }

        setWarnings(newWarnings);
        setIsValid(newIsValid);
        onValidationChange?.(newIsValid, newWarnings);
    }, [type, parentSlug, onValidationChange]);

    // Check if slug already exists
    const checkSlugExists = useCallback(async (slugValue: string): Promise<boolean> => {
        if (!slugValue) return false;

        setIsChecking(true);
        try {
            const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3003/api/v1';
            let endpoint = '';

            switch (type) {
                case 'service':
                    endpoint = '/services/check-slug';
                    break;
                case 'subservice':
                    endpoint = '/sub-services/check-slug';
                    break;
                case 'page':
                    endpoint = '/pages/check-slug';
                    break;
                case 'asset':
                    endpoint = '/assets/check-slug';
                    break;
            }

            const response = await fetch(`${apiUrl}${endpoint}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ slug: slugValue }),
            });

            const result = await response.json();
            return result.exists || false;
        } catch (error) {
            console.error('Error checking slug:', error);
            return false;
        } finally {
            setIsChecking(false);
        }
    }, [type]);

    // Auto-generate slug when title changes
    useEffect(() => {
        if (title && isAutoGenerated && !disabled) {
            const newSlug = generateSlugFromTitle(title);
            const newFullUrl = generateFullUrl(newSlug);

            setSlug(newSlug);
            setFullUrl(newFullUrl);
            onSlugChange(newSlug);
            onFullUrlChange(newFullUrl);
            validateSlugAndUrl(newSlug, newFullUrl);
        }
    }, [title, isAutoGenerated, disabled, generateSlugFromTitle, generateFullUrl, onSlugChange, onFullUrlChange, validateSlugAndUrl]);

    // Handle slug change
    const handleSlugChange = async (value: string) => {
        setSlug(value);
        setIsAutoGenerated(false);

        const newFullUrl = generateFullUrl(value);
        setFullUrl(newFullUrl);

        onSlugChange(value);
        onFullUrlChange(newFullUrl);

        validateSlugAndUrl(value, newFullUrl);

        // Check if slug exists (debounced)
        if (value && isValid) {
            const exists = await checkSlugExists(value);
            if (exists) {
                setWarnings(prev => [...prev, 'This slug already exists. Consider using a different one.']);
                setIsValid(false);
            }
        }
    };

    // Handle full URL change
    const handleFullUrlChange = (value: string) => {
        setFullUrl(value);
        onFullUrlChange(value);
        validateSlugAndUrl(slug, value);
    };

    // Regenerate slug from title
    const handleRegenerateSlug = () => {
        const newSlug = generateSlugFromTitle(title);
        const newFullUrl = generateFullUrl(newSlug);

        setSlug(newSlug);
        setFullUrl(newFullUrl);
        setIsAutoGenerated(true);

        onSlugChange(newSlug);
        onFullUrlChange(newFullUrl);
        validateSlugAndUrl(newSlug, newFullUrl);
    };

    return (
        <div className="space-y-4">
            {/* Full URL Field */}
            <div>
                <label className="block text-sm font-semibold text-slate-700 mb-2">
                    🔗 Full URL
                </label>
                <div className="relative">
                    <input
                        type="text"
                        value={fullUrl}
                        onChange={(e) => handleFullUrlChange(e.target.value)}
                        disabled={disabled}
                        placeholder="/services/your-service-slug"
                        className={`w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 transition-all font-mono text-sm ${!isValid
                                ? 'border-red-300 bg-red-50'
                                : 'border-slate-300 bg-white'
                            } ${disabled ? 'opacity-50 cursor-not-allowed' : ''}`}
                    />
                    {baseUrl && (
                        <div className="absolute left-3 top-1/2 transform -translate-y-1/2 text-xs text-slate-400">
                            {baseUrl}
                        </div>
                    )}
                </div>
            </div>

            {/* URL Slug Field */}
            <div>
                <div className="flex items-center justify-between mb-2">
                    <label className="block text-sm font-semibold text-slate-700">
                        🔤 URL Slug
                    </label>
                    {title && !disabled && (
                        <button
                            type="button"
                            onClick={handleRegenerateSlug}
                            className="text-xs text-blue-600 hover:text-blue-700 font-medium"
                        >
                            🔄 Regenerate from Title
                        </button>
                    )}
                </div>
                <div className="relative">
                    <input
                        type="text"
                        value={slug}
                        onChange={(e) => handleSlugChange(e.target.value)}
                        disabled={disabled}
                        placeholder={placeholder}
                        className={`w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 transition-all ${!isValid
                                ? 'border-red-300 bg-red-50'
                                : isAutoGenerated
                                    ? 'border-amber-300 bg-amber-50'
                                    : 'border-slate-300 bg-white'
                            } ${disabled ? 'opacity-50 cursor-not-allowed' : ''}`}
                    />
                    {isAutoGenerated && (
                        <div className="absolute right-3 top-1/2 transform -translate-y-1/2">
                            <span className="text-xs text-amber-600 font-medium">Auto</span>
                        </div>
                    )}
                    {isChecking && (
                        <div className="absolute right-3 top-1/2 transform -translate-y-1/2">
                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600"></div>
                        </div>
                    )}
                </div>
                {isAutoGenerated && (
                    <p className="text-xs text-amber-600 mt-1">
                        ⚡ Auto-generated from title. Click to edit manually.
                    </p>
                )}
            </div>

            {/* Validation Messages */}
            {warnings.length > 0 && (
                <div className={`p-3 rounded-lg ${isValid ? 'bg-amber-50 border border-amber-200' : 'bg-red-50 border border-red-200'}`}>
                    <div className="flex items-start">
                        <span className={`text-sm ${isValid ? 'text-amber-600' : 'text-red-600'} mr-2`}>
                            {isValid ? '⚠️' : '❌'}
                        </span>
                        <div className="flex-1">
                            {warnings.map((warning, index) => (
                                <p key={index} className={`text-xs ${isValid ? 'text-amber-700' : 'text-red-700'} ${index > 0 ? 'mt-1' : ''}`}>
                                    {warning}
                                </p>
                            ))}
                        </div>
                    </div>
                </div>
            )}

            {/* Success Message */}
            {isValid && slug && warnings.length === 0 && (
                <div className="p-3 bg-green-50 border border-green-200 rounded-lg">
                    <div className="flex items-center">
                        <span className="text-green-600 mr-2">✅</span>
                        <p className="text-xs text-green-700">
                            URL structure is valid and follows best practices.
                        </p>
                    </div>
                </div>
            )}

            {/* URL Preview */}
            {fullUrl && (
                <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg">
                    <p className="text-xs font-semibold text-slate-600 mb-1">Preview:</p>
                    <a
                        href={fullUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-sm text-blue-600 hover:text-blue-700 font-mono break-all"
                    >
                        {fullUrl}
                    </a>
                </div>
            )}
        </div>
    );
};

export default UrlSlugManager;
